# Chave única do projeto no SonarCloud
sonar.projectKey=uf-cicd-calcjs-Anna-Vitoria

# Organização do projeto no SonarCloud
sonar.organization=annavihm

# Linguagem principal do projeto
sonar.language=js

# Diretório com código fonte a ser analisado
sonar.sources=./src

# Diretório dos testes
sonar.tests=./tests

# Informa o nome da branch padrão (geralmente "main")
sonar.branch.name=main

bb42d4c7d8907aa592b107f9503679f02e4ba0fd